[versions]
android = "7.0.4"
benManes = "0.42.0"
changelog = "1.3.1"
detekt = "1.19.0"
dokka = "1.6.10"
gradlePublish = "0.21.0"
javierscGradlePlugins = "0.1.0-rc.41"
javierscSemverGradlePlugin = "0.1.0-alpha.10"
kotlin = "1.6.20"
kotlinBinaryValidator = "0.8.0"
kover = "0.5.0"
mkdocs = "2.3.0"
nexusPublish = "1.1.0"
sonarqube = "3.3"
spotless = "6.4.1"
testLogger = "3.2.0"
tripleT = "3.7.0"

[libraries]
adarshr-gradleTestLoggerPlugin = { module = "com.adarshr:gradle-test-logger-plugin", version.ref = "testLogger" }
android-toolsBuild-gradle = { module = "com.android.tools.build:gradle", version.ref = "android" }
diffplug-spotless-spotlessPluginGradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
github-benManes-gradleVersionsPlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "benManes" }
github-gradleNexus-publishPlugin = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexusPublish" }
github-tripletGradle-playPublisher = { module = "com.github.triplet.gradle:play-publisher", version.ref = "tripleT" }
gitlab-arturboschDetekt-detektGradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-publish-pluginPublishPlugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradlePublish" }
javiersc-gradlePlugins-allPlugins = { module = "com.javiersc.gradle-plugins:all-plugins", version.ref = "javierscGradlePlugins" }
javiersc-semver-semverGradlePlugin = { module = "com.javiersc.semver:semver-gradle-plugin", version.ref = "javierscSemverGradlePlugin" }
jetbrains-dokka-dokkaGradlePlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
jetbrains-intellijPlugins-gradleChangelogPlugin = { module = "org.jetbrains.intellij.plugins:gradle-changelog-plugin", version.ref = "changelog" }
jetbrains-kotlin-kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinBinaryValidator" }
jetbrains-kotlinx-kover = { module = "org.jetbrains.kotlinx:kover", version.ref = "kover" }
sonarqube-scannerGradle-sonarqubeGradlePlugin = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref = "sonarqube" }
vyarus-gradleMkdocsPlugin = { module = "ru.vyarus:gradle-mkdocs-plugin", version.ref = "mkdocs" }
