[versions]
android = "7.0.3"
benManes = "0.39.0"
changelog = "1.3.1"
detekt = "1.18.1"
dokka = "1.5.31"
gradleEnterprise = "3.7.1"
gradlePublish = "0.17.0"
javierscGradlePlugins = "0.1.0-rc.11"
javierscSemverGradlePlugin = "0.1.0-alpha.2"
kotlin = "1.5.31"
kotlinBinaryValidator = "0.8.0"
mkdocs = "2.1.1"
nexusPublish = "1.1.0"
spotless = "6.0.0"
testLogger = "3.1.0"

[libraries]
adarshr-gradleTestLoggerPlugin = { module = "com.adarshr:gradle-test-logger-plugin", version.ref = "testLogger" }
android-toolsBuild-gradle = { module = "com.android.tools.build:gradle", version.ref = "android" }
diffplug-spotless-spotlessPluginGradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
github-benManes-gradleVersionsPlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "benManes" }
github-gradleNexus-publishPlugin = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexusPublish" }
gitlab-arturboschDetekt-detektGradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-enterprise-comGradleEnterpriseGradlePlugin = { module = "com.gradle.enterprise:com.gradle.enterprise.gradle.plugin", version.ref = "gradleEnterprise" }
gradle-publish-pluginPublishPlugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradlePublish" }
javiersc-gradlePlugins-allPlugins = { module = "com.javiersc.gradle-plugins:all-plugins", version.ref = "javierscGradlePlugins" }
javiersc-semver-semverGradlePlugin = { module = "com.javiersc.semver:semver-gradle-plugin", version.ref = "javierscSemverGradlePlugin" }
jetbrains-dokka-dokkaGradlePlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
jetbrains-intellijPlugins-gradleChangelogPlugin = { module = "org.jetbrains.intellij.plugins:gradle-changelog-plugin", version.ref = "changelog" }
jetbrains-kotlin-kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinBinaryValidator" }
vyarus-gradleMkdocsPlugin = { module = "ru.vyarus:gradle-mkdocs-plugin", version.ref = "mkdocs" }
