site_name: Gradle Plugins
site_description: Gradle Plugins utilities
site_author: Javier Segovia Córdoba
remote_branch: gh-pages

repo_name: Gradle Plugins
repo_url: https://github.com/JavierSegoviaCordoba/gradle-plugins

copyright: 'Copyright &copy; 2021 Javier Segovia Córdoba'

theme:
  name: 'material'
  language: 'en'
  favicon: 'assets/favicon-512.png'
  logo: 'assets/favicon-512.png'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Fira Sans'
    code: 'JetBrains Mono'

nav:
  - Overview: index.md

plugins:
  - search

markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: True
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JavierSegoviaCordoba
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JavierSegoviaCo

extra_css:
  - css/all.css
