name: build-renovate

on:
  pull_request:
    branches:
      - 'renovate/**'
    paths:
      - '!**/CHANGELOG.md'

jobs:
  add-updated-dependencies-to-changelog:
    runs-on: ubuntu-latest

    needs:
      - build-pull-request

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          github_token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      - name: Set up Java
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Add updated dependencies to the CHANGELOG from Renovate
        if: ${{ (github.event_name == 'pull_request') && (github.event.pull_request.user.login == 'renovate[bot]') }}
        run: |
          git switch -c ${{ github.event.pull_request.head.ref }}
          ./gradlew addChangelogItem --renovateCommitTable
          git config --global user.email "javier@segoviacordoba.com"
          git config --global user.name "Javier Segovia CÃ³rdoba"
          git add .
          git commit --amend --no-edit
          git push --set-upstream origin ${{ github.event.pull_request.head.ref }} --force

      - name: Change PR to be ready for review
        run: gh pr ready
