name: publish-kotlin

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/publish-kotlin.yaml@main
    with:
      publish-maven-central: true
      publish-gradle-plugin-portal: true
      publish-jetbrains-marketplace: false
      publish-docs: true
      publish-github-release: true
    secrets:
      TOKEN_GITHUB_ACTION: '${{ secrets.GITHUB_TOKEN }}'
      OSS_USER: '${{ secrets.OSS_USER }}'
      OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
      OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
      SIGNING_KEY_NAME: '${{ secrets.SIGNING_KEY_NAME }}'
      SIGNING_KEY_ID: '${{ secrets.SIGNING_KEY_ID }}'
      SIGNING_KEY_PASSPHRASE: '${{ secrets.SIGNING_KEY_PASSPHRASE }}'
      SIGNING_KEY: '${{ secrets.SIGNING_KEY }}'
      GRADLE_PUBLISH_KEY: '${{ secrets.GRADLE_PUBLISH_KEY }}'
      GRADLE_PUBLISH_SECRET: '${{ secrets.GRADLE_PUBLISH_SECRET }}'
